services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    security.user_password_encoder.generic:
        class: 'Symfony\Component\Security\Core\Encoder\UserPasswordEncoder'
        public: true